defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "Carebest"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">Carebest 家倍安社會企業</a>"

development:
  <<: *defaults
  authenticators:
    carebest:
      class: "CASino::ActiveRecordModelAuthenticator"
      options:
        connection:
          adapter: "mysql2"
          host: "localhost"
          username: "root"
          password: "anaircqweqwe"
          database: "articles"
        table: "kwuser"
        username_column: "email"
        password_column: "userPassword"
        extra_attributes:
          email: "email"
          fullname: "userFullname" 
  
test:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"

production:
  <<: *defaults
  authenticators:
    my_user_database:
    authenticator: "ActiveRecord"
    options:
      connection:
        adapter: "mysql2"
        host: "localhost"
        username: "root"
        password: "anaircqweqwe"
        database: "articles"
      table: "kwuser"
      username_column: "email"
      password_column: "userPassword"
      extra_attributes:
        email: "email"
        fullname: "userFullname"