development: 
  :address: "smtp.gmail.com"
  :port: 587
  :authentication: :plain
  :user_name: "service@carebest.com.tw"
  :password: "carebest.tw88"
  :domain: "www.carebest.com.tw"  

production:
  :address: "smtp.gmail.org"
  :port: 587
  :authentication: :plain
  :user_name: "service@carebest.com.tw"
  :password: "carebest.tw88"
  :domain: "www.carebest.com.tw"  